# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jonas Trevisan
tagline:          'Jonhkr'
description:      ''
url:              http://jonhkr.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jonhkr/jonhkr.github.io
